# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgcCli < Formula
  desc "AppGallery Connect command center"
  homepage "https://github.com/Createitv/agc-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Createitv/agc-cli/releases/download/v0.1.0/agc-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "724c03182d08bb9bb8b3a4ae2a79b7239e4fbbb2f159f947f536051fdff823ca"

      define_method(:install) do
        bin.install "agc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Createitv/agc-cli/releases/download/v0.1.0/agc-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "342fec7432a4e1913d3b425fb941108194445f921704449446232b0858b0f5e1"

      define_method(:install) do
        bin.install "agc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Createitv/agc-cli/releases/download/v0.1.0/agc-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "65b537d8913a7072ae0dfded0e2a196adde8a239bc248ae752d5a16b3ced350c"
      define_method(:install) do
        bin.install "agc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Createitv/agc-cli/releases/download/v0.1.0/agc-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "0af553146e367124ef94fe84d841579426cd37e1ecdf544ca30fe82ad8878ba8"
      define_method(:install) do
        bin.install "agc"
      end
    end
  end
end
